### ISSUE TITLE
Second display set as extended shows incorrect size in DX11 mode

### ISSUE THREAD

**Issue by WvsPiV5** [sabaatworld/HyperionScreenCap#21]
In Windows 10, second screen set as extended.

If it is left or right of the main display, the horizontal size is incorrectly reported. If it is left, the size is 0, if it is right, then the size of the main display is added to the actual size of the second display.

```
[INFO] [1] HyperionScreenCap.SetupForm.lblShowDx11Displays_LinkClicked:0 - Available Monitors: Adapter Index 0: NVIDIA GeForce GTX 1080
	Monitor Index 0: \\.\DISPLAY1 3440×1440
	Monitor Index 1: \\.\DISPLAY2 0×2160

[INFO] [1] HyperionScreenCap.SetupForm.lblShowDx11Displays_LinkClicked:0 - Available Monitors: Adapter Index 0: NVIDIA GeForce GTX 1080
	Monitor Index 0: \\.\DISPLAY1 3440×1440
	Monitor Index 1: \\.\DISPLAY2 7280×2160
```

The same happens if they are ontop of each other.

```
[INFO] [1] HyperionScreenCap.SetupForm.lblShowDx11Displays_LinkClicked:0 - Available Monitors: Adapter Index 0: NVIDIA GeForce GTX 1080
	Monitor Index 0: \\.\DISPLAY1 3440×1440
	Monitor Index 1: \\.\DISPLAY2 3840×0

[INFO] [1] HyperionScreenCap.SetupForm.lblShowDx11Displays_LinkClicked:0 - Available Monitors: Adapter Index 0: NVIDIA GeForce GTX 1080
	Monitor Index 0: \\.\DISPLAY1 3440×1440
	Monitor Index 1: \\.\DISPLAY2 3840×3600
```

The capture is therefore not really working or producing an error (if 0 is detected). Everything works fine in DX9 mode.

**Comment by sabaatworld** [comment]
Interesting! I had never tested out with the extended monitor setup since I don't have a second monitor. Will try to find out what's going on.

**Comment by TheAndi** [comment]
![image](https://user-images.githubusercontent.com/33332336/43600869-19edadde-968c-11e8-9e00-dd472ee2cf8e.png)

![image](https://user-images.githubusercontent.com/33332336/43600970-5a7d65b0-968c-11e8-8407-3c038249bdc5.png)

1st Monitor: 3840x2160
2nd Monitor: 1920x1080

Have got the same problem. The wrong resolution corresponds with the windows screen position as well.

Would be awesome if this could be fixed.

Thanks in advance!

**Comment by pilonull** [comment]
![image](https://user-images.githubusercontent.com/8344590/46512147-67c0d700-c820-11e8-8f28-a6054f04cc7d.png)

I am also having this issue... Was hoping to find a fix for it :(

**Comment by sabaatworld** [comment]
This issue is now fixed. Please download and install v2.6. Note that if "Check for Updates" option does not work, you will need to manually download the update from GitHub.

Let me know if the problem got fixed.
