### ISSUE TITLE
DX11 Problem with HDMI Splitter

### ISSUE THREAD

**Issue by janpfischer** [sabaatworld/HyperionScreenCap#22]
Hi,

as mentioned before in hyperion forum thanks a lot for your work! 
I am now using your app and facing a problem:

I am using a hdmi splitter connected to my hdmi graphic card port. 1 output is going to my 2nd monitor and 1 output is going to the tv. Now if i want to select this monitor for caputring DX11 thinks the resolution is 3840x1080 instead of 1920x1080. So the screen is black for hyperion at the middle to the right. 

In DX9 Mode all is fine. 

Best regards.

**Comment by sabaatworld** [comment]
Can you please post information about your displays as shown in Hyperion settings? There should be a link in there for viewing this information.

**Comment by janpfischer** [comment]
It seems to be the same as the post in the Hyperion forum you answered yesterday. 

I also have sometimes the issue that the display information says that my 2nd monitor has a resolution of 0x1080. I am also running extended setup mode. With DX9 there is no problem. So now I don't think there is a problem with the splitter. I think it has something to do with extended setup and grabbing 2nd monitor. 

I will post a screenshot as soon I am home

EDIT: Ok, i think it have nothing to do with the splitter. I have connected my 3rd monitor (tv) now directly to the graphics card and mirored my monitor 1 to monitor 3. 
This is a screen from my setup.
![image](https://user-images.githubusercontent.com/5278602/41192423-a7b93322-6bfd-11e8-81d9-c301815a864c.png)

**Comment by WvsPiV5** [comment]
This is actually the same as reported with issue #21

**Comment by sabaatworld** [comment]
This issue is now fixed. Please download and install v2.6. Note that if "Check for Updates" option does not work, you will need to manually download the update from GitHub.

Let me know if the problem got fixed.

**Comment by janpfischer** [comment]
Problem is fixed. Thanks a lot! Now I can finally using DX11 :)
