### ISSUE TITLE
System.Exception: Failed to initialize screen capture: HRESULT: [0x887A0002]

### ISSUE THREAD

**Issue by IIIdefconIII** [sabaatworld/HyperionScreenCap#24]
Keep getting the following errors in log. Hyperion works normally and i can load effects and colours with WSL Ubuntu. I have windows 10 1803, it runs DX12, i tried alot like installing 3dmark11 (hoped that it would bring dx11). I just cant get it to work. Any ideas?

System.Exception: Failed to initialize screen capture: HRESULT: [0x887A0002], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_FOUND/NotFound], Message: The object was not found. If calling IDXGIFactory::EnumAdaptes, there is no adapter with the specified ordinal.

System.Exception: Failed to initialize screen capture: HRESULT: [0x887A0002], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_FOUND/NotFound], Message: The object was not found. If calling IDXGIFactory::EnumAdaptes, there is no adapter with the specified ordinal.

System.Exception: Failed to initialize screen capture: HRESULT: [0x887A0002], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_FOUND/NotFound], Message: The object was not found. If calling IDXGIFactory::EnumAdaptes, there is no adapter with the specified ordinal.

**Comment by IIIdefconIII** [comment]
? is this still under development / support?

**Comment by sabaatworld** [comment]
Hi

Are you still facing this problem? From the error message it seems like the display could not be found by the software. Can you post a screenshot of "view dx11 monitors" option on the settings screen?

Also, it would be helpful if you can include the log file.

**Comment by IIIdefconIII** [comment]
i moved back to ubuntu cause of this 👍
