### ISSUE TITLE
Is this still maintained? Looking for assistance using Windows 10

### ISSUE THREAD

**Issue by pilonull** [sabaatworld/HyperionScreenCap#25]
![image](https://user-images.githubusercontent.com/8344590/46514091-c76fb000-c829-11e8-8316-26d85c6d9b84.png)

Obviously these resolutions are incorrect. I have 3 displays connected to my PC. Main monitor is 2560x1440, monitor on the right is 1920x1080, and a 4k tv on the left. 

I have hyperion and the LEDs installed on the 4k tv but cannot get hyperionscreencap to capture the TV images. I have tried both DX9 and DX11. DX9 is broken and does not enable any LEDs no matter how i configure it. 

I really wish this was still being worked on because I think it's a fantastic companion to Hyperion.

Thanks

**Comment by sabaatworld** [comment]
This issue is now fixed. Please download and install v2.6. Note that if "Check for Updates" option does not work, you will need to manually download the update from GitHub.

**Comment by sabaatworld** [comment]
Let me know if the issue got fixed for you.

**Comment by pilonull** [comment]
YOU THE MAN! THANK YOU SO MUCH!
