### ISSUE TITLE
Exception in screen capture attempt: 1

### ISSUE THREAD

**Issue by bastianum** [sabaatworld/HyperionScreenCap#26]
Hey!

First of all, great work here!
I get the connection established, no errors there. As soon as I start a YT Video though, I get this error:

2018-10-24 13:49:59 [ERROR] [5] HyperionScreenCap.Helper.HyperionTask.StartCapture:0 - HyperionTask[ConfigurationId: 1c49f1]: Exception in screen capture attempt: 1
System.Exception: Error occured while sending image to server: In die Übertragungsverbindung können keine Daten geschrieben werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.IO.IOException: In die Übertragungsverbindung können keine Daten geschrieben werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
bei System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
bei System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
--- Ende der internen Ausnahmestapelüberwachung ---
bei System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
bei HyperionScreenCap.ProtoClient.SendRequest(IMessageLite request)
bei HyperionScreenCap.ProtoClient.SendImageToServer(Byte[] pixeldata, Int32 width, Int32 height)
bei HyperionScreenCap.Helper.HyperionTask.TransmitNextFrame()
--- Ende der internen Ausnahmestapelüberwachung ---
bei HyperionScreenCap.Helper.HyperionTask.TransmitNextFrame()
bei HyperionScreenCap.Helper.HyperionTask.StartCapture()

It basically says that he is not able to write data into the connection tunnel - do you have any clue what happens there or how I can solve that?

Thanks in advance,

Bastian

**Comment by sabaatworld** [comment]
Seems like your Hyperion server's proto port is not enabled or it might be using a different port. The IP address might also be incorrect.

**Comment by bastianum** [comment]
Hi sabaat, the connection works fine. The log says connection established. It just gives this error when it is starting the screen capture process automatically when I start a YouTube video or an game.. needs to be something different.

**Comment by sabaatworld** [comment]
It still seems like some network related thing even if the initial connection got established somehow. Maybe you need to whitelist the app in your firewall?
