### ISSUE TITLE
Netflix on Edge doesn't work

### ISSUE THREAD

**Issue by shad00m** [sabaatworld/HyperionScreenCap#29]
It works fine when I'm watching Netflix in chrome but not in Edge.
I assume it's because of their copy protection or something?
In edge the LEDs just stay black.

**Comment by janpfischer** [comment]
Yep. This is DRM Feature from Microsoft and Edge. Which is required to enable 4K Videos in Windows on Netflix. 
Think this application can do nothing against it.

**Comment by sabaatworld** [comment]
Yes. Nothing can be done about this.

**Comment by laurens94** [comment]
I guess for this to work is to use an HDMI grabber instead of ScreenCapture right?

**Comment by sabaatworld** [comment]
Everything you connect to HDMI must be HDCP 2.2 compliant. Then it will most likely work.

But since these things are expensive, you may want to check on Hyperion forums before buying.
