### ISSUE TITLE
Add Flatbuffers support

### ISSUE THREAD

**Issue by janpfischer** [sabaatworld/HyperionScreenCap#30]
Hi,

since Hyperion.ng is moved to flatbuffer and removed protobuff can we look into implementing flatbuffer in hyperionscreencap?

If I connect hyperionscreencap to flatbuffer no data is transferred.

I could help with testing if you want.

**Comment by sabaatworld** [comment]
Does the app not work at all with new Hyperion versions?

**Comment by jonty-comp** [comment]
After some trouble I believe the dev who replaced Protobuf with Flatbuf
ended up reimplementing both, but recommends Flatbuf for future
implementations.

**Comment by janpfischer** [comment]
We implemented both to give apps like this the chance to update or maybe implement both. 
Protobuf will be deleted again. Then this software will not work with all future hyperion.ng versions.

**Comment by jay9ee** [comment]
Protobuf doesn't seem to be working anymore on new hyperion.ng versions.

**Comment by janpfischer** [comment]
On Alpha.4 it is working for me.

**Comment by jay9ee** [comment]
For me Hyperion screen capture says it connected successfully but it doesn't show up on Hyperion ng source selection, neither on a raspberry nor on my PC running Hyperion ng on Linux Mint, I tried binary and self compiled versions on both.

**Comment by janpfischer** [comment]
Which priority do you have selected in hyperscreencap?

**Comment by jay9ee** [comment]
Well color me dumb. I tried with different values before but it didn't want to work maybe I tried values too high actually. Now with priority 160 it works. On the standard 10 it doesn't work tho.

**Comment by janpfischer** [comment]
Yeah would be good to change the standard here since Hyperion.ng only allows priorities between 100-254. all other are reserved internally

**Comment by IATkachenko** [comment]
Is any news about Flatbuffers for ScreenCap?

**Comment by sabaatworld** [comment]
I'm not well versed with either but I think we need to start with getting the flat buffer object definitions. Can someone point them out?

**Comment by sabaatworld** [comment]
I've implemented flat buffer support in the latest commit but I don't have Hyperion set up. Can anybody test it?

**Comment by sabaatworld** [comment]
Nevermind, I tested it out as well and its working. Will include in next release.

**Comment by sabaatworld** [comment]
New release is out now. Please open another issue if flat buffer does not work.
