### ISSUE TITLE
[Feature request] Combine multiple Monitors and send 1 (big screen) to hyperion

### ISSUE THREAD

**Issue by hannesroth88** [sabaatworld/HyperionScreenCap#38]
Hi, 
in my setup i would like to have a single RaspberryPi and Ambilight around my 3 Monitors (Extended Displays).
Therefore I thought about reading the 3 display ports merge them to 1 fictive big screen and then send it over Hyperion.

Do you think this is even possible? I just don't have a clue where to start, so it would be great if someone could give me starting point or directly tell me it's a bad idea :).

**Comment by sabaatworld** [comment]
Don't know why this didn't come up earlier. Seems like a good idea to be honest.

Off the top of my head, it seems like the issue could be combine screen captures from multiple screens continuously. That may use up too much CPU. I don't remember coming across an API that would allow me to capture all screens in one go (or maybe I missed something).

As an alternate, you may be able to run multiple copies of Hyperion on a single RPi. If by default, they don't allow you, then you can checkout the code and compile slightly different variants of Hyperion that can run together.

**Comment by jdarmetzki** [comment]
I actually have a triple screen setup, and my solution is running 3 instances of Hyperion on the RPi

**Comment by sabaatworld** [comment]
Can we mark this as resolved?

**Comment by hannesro** [comment]
Didn't have time to elaborate more on this.
Having two more rpi was what I wanted to avoid. But at least a solution how to do it.

**Comment by jdarmetzki** [comment]
> 
> 
> Didn't have time to elaborate more on this.
> Having two more rpi was what I wanted to avoid. But at least a solution how to do it.

I got 3 instances running on a single RPI 3 - no need for multiple

**Comment by Guyohms** [comment]
With the Windows version of Hyperion, one can grab all monitors at once using QT

![image](https://user-images.githubusercontent.com/44414660/126880047-0fa271f2-7a36-47e5-9d37-00e2880d8f81.png)

It would be great to utilize the same method for ScreenCap !
That way, the the Hyperion server can be run outside of the Windows machine and just use the ScreenCap which uses very few ressources compared to using the Windows Hyperion install.

**Comment by sabaatworld** [comment]
Are you suggesting that QT screen capture is much more efficient than the DirectX capture method?

**Comment by Guyohms** [comment]
No, but I guess that not having to run Hyperion on the windows machine could free some CPU usage.

I agree that DX seems more efficient, but it looks like it cannot be used to capture the whole layout as a virtual monitor.
If it can, that would be an awesome upgrade!
