### ISSUE TITLE
Binary Release

### ISSUE THREAD

**Issue by jjhidalgar** [sabaatworld/HyperionScreenCap#40]
Hi! Thanks for this awesome project. 

Can anyone share the compiled binary for the latest release? It looks like the latest release is 2.6. I'll try to compile it from source else, just wondering in case you have it in hand.

**Comment by sabaatworld** [comment]
There were only minor changes made since the last release. That's why didn't create a new release yet.

**Comment by sabaatworld** [comment]
Isn't the latest release for 2.6?

**Comment by jjhidalgar** [comment]
Oh my bad, you are right. I saw the screenshot and looked different, so for some reason I thought there was a higher version.  Also because release dates from 2018 and there have been changes after that
