### ISSUE TITLE
Is it possible to define a custom Image Scaling Factor?

### ISSUE THREAD

**Issue by laurens94** [sabaatworld/HyperionScreenCap#41]
My ideal Image Scaling Factor is somewhere between 64 and 128. Is there a reason these values are predefined instead of allowing for a whole range of numbers?

Thanks for maintaining this software btw, I just donated you a coffee! ☕ 👍

**Comment by sabaatworld** [comment]
Coffee was super. Thanks!

Those scaling factors need to be in powers of 2 so I made a drop down to make things a bit easy.

**Comment by sabaatworld** [comment]
Btw, you can use this video to check if lights are lagging behind or not https://youtu.be/8u4UzzJZAUg

**Comment by laurens94** [comment]
That makes sense, thanks! :D
