### ISSUE TITLE
Windows UI scaling factor

### ISSUE THREAD

**Issue by laurens94** [sabaatworld/HyperionScreenCap#43]
I have 2 monitors (pc and tv). My tv has display scaling set to 200% in windows display settings.
The UI of HyperionScreenCap context menu (right click on tray icon) is scaled according to the display that's active when the app launches, but whenever I switch while the app is already open, the scaling factor is not being applied.

![image](https://user-images.githubusercontent.com/5780704/100476725-a42dac00-30e6-11eb-896b-117556a03015.png)

The problem is not that big, because I can just restart Hyperion Screen Capture and the scaling is applied correctly for the context menu. However, in that case the config panel is not scaling correctly:

![image](https://user-images.githubusercontent.com/5780704/100476701-911adc00-30e6-11eb-91d5-ce620483ebd2.png)

**Comment by sabaatworld** [comment]
See the compatibility section on https://support.microsoft.com/en-us/help/3025083/windows-scaling-issues-for-high-dpi-devices

**Comment by sabaatworld** [comment]
Feel free to reopen if you need help.
