### ISSUE TITLE
Led doesn't turn off on Windows shutdown.

### ISSUE THREAD

**Issue by 0-Pierre** [sabaatworld/HyperionScreenCap#44]
Hi, 

I use an Arduino Uno and Hyperion, everything works well but when I shutdown my PC the led are turned on I must quit the soft before shuting down Windows and when i forgot i have to unplug the led power cable..

Do you have any solutions ?

**Comment by sabaatworld** [comment]
Newly released v2.9 has modified retry behavior which might fix this issue.
