### ISSUE TITLE
Not recording screen properly when playing Minecraft

### ISSUE THREAD

**Issue by theTobster500** [sabaatworld/HyperionScreenCap#64]
as soon as I open Minecraft, the screen recording starts stuttering heavily, like a frame update every few seconds, until it just completely stops recording and I have to restart it. Not an issue with most other games, specifically with Minecraft Java edition as far as I have seen.

**Comment by Xitee1** [comment]
I don't have that problem with Minecraft Java. It works without problem for me.

**Comment by theTobster500** [comment]
works with my new amd card (5700 xt) now too, didn't work on my gtx 1060

**Comment by Xitee1** [comment]
I also have an gtx 1060 :shrug:
