### ISSUE TITLE
2 Port for 2 Hyperion server 

### ISSUE THREAD

**Issue by Moimemeici** [sabaatworld/HyperionScreenCap#9]
Hello,

sorry for my english but can you add possibility for 2 port ?
When we use Hyperion x2 on server, for led behind TV and other for example Philips Hue Control ?

Sorry again for my english.

best regards

**Comment by sabaatworld** [comment]
Which capture mode are you using for windows grabber, DirectX9 or DirectX11?

**Comment by Moimemeici** [comment]
I have:
hyperion installed on debian.
Computer windows with Hyperion screen Capture.
Arduino for Led conntected with usb on my server debian.
i need control my led and my philips hue, i make 2x  Hyperion on server.
One with port 19445 and other with port 19446

**Comment by sabaatworld** [comment]
I will try to add support for this soon.

**Comment by sabaatworld** [comment]
The latest release (2.3) add supports for multiple displays and multiple Hyperion servers. Download it here: https://github.com/sabaatworld/HyperionScreenCap/releases

Let me know if you face any issues.

**Comment by Moimemeici** [comment]
Wahou 
Very thank you.
It's very fine, All worked !

**Comment by sabaatworld** [comment]
Awesome! Just one thing to note here is that when you want to send the same captured screen to multiple Hyperion servers then create just one capture configuration with two Hyperion servers.

I'm marking this issue as resolved.
